# Generated by Django 4.0.1 on 2022-05-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='question')),
                ('answer', models.CharField(blank=True, max_length=255, null=True, verbose_name='answer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
