# Generated by Django 4.0 on 2022-01-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_code_book_mode_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='book',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='firstname'),
        ),
        migrations.AddField(
            model_name='book',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='lastname'),
        ),
        migrations.AddField(
            model_name='book',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='middlename'),
        ),
    ]
