# Generated by Django 4.0 on 2022-01-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_customer_name_book_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='package',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='package'),
        ),
    ]
