# Generated by Django 4.0 on 2022-01-15 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined'),
        ),
    ]
