# Generated by Django 4.0 on 2022-01-15 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='book',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='transaction_date'),
        ),
    ]
