# Generated by Django 4.0 on 2022-01-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_book_date_joined_book_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subtype'),
        ),
    ]
