# Generated by Django 4.0 on 2022-01-16 00:51

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='proofOfPayment',
            field=models.ImageField(default='uploads/book.png', upload_to=book.models.nameFile, verbose_name='proofOfPayment'),
        ),
        migrations.AddField(
            model_name='book',
            name='to_pay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='to_pay'),
        ),
    ]
