# Generated by Django 4.0 on 2022-01-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_image_book_proofofpayment_book_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='transaction_date',
            field=models.DateTimeField(verbose_name='transaction_date'),
        ),
    ]
