# Generated by Django 4.0 on 2022-01-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction_date'),
        ),
    ]
