# Generated by Django 4.0.1 on 2022-01-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_book_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='promoCode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='promoCode'),
        ),
    ]
