# Generated by Django 4.0.1 on 2022-05-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_book_checkin_time_book_checkout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkin_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='checkin_time'),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkout_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='checkout_time'),
        ),
    ]
