# Generated by Django 4.0.1 on 2022-05-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_book_ad_other_book_ad_other_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_paid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='total_paid'),
        ),
    ]
