# Generated by Django 4.0.1 on 2022-02-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('action', models.CharField(blank=True, max_length=255, null=True, verbose_name='action')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
