# Generated by Django 4.0.1 on 2022-03-23 05:12

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.CharField(blank=True, max_length=255, null=True, verbose_name='contacts')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('history', models.CharField(blank=True, max_length=255, null=True, verbose_name='history')),
                ('carousel1', models.ImageField(default='uploads/Content.png', upload_to=settings.models.nameFile, verbose_name='carousel1')),
                ('carousel2', models.ImageField(default='uploads/Content.png', upload_to=settings.models.nameFile, verbose_name='carousel2')),
                ('carousel3', models.ImageField(default='uploads/Content.png', upload_to=settings.models.nameFile, verbose_name='carousel3')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
