# Generated by Django 4.0 on 2022-01-13 13:28

from django.db import migrations, models
import rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='service_type')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='price')),
                ('package', models.CharField(blank=True, max_length=255, null=True, verbose_name='package')),
                ('image', models.ImageField(default='uploads/pools.png', upload_to=rooms.models.nameFile, verbose_name='image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
