# Generated by Django 4.0.1 on 2022-02-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rooms_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_features',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='room_features'),
        ),
    ]
